from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
import smtplib

# Sender Mail Configuration
SENDER_EMAIL = "dungavathpradeepnaik123@gmail.com"
APP_PASSWORD = "ezbb fkpv uald mlur"  # 16-character Google App Password


def send_email_alert(to_email, candidate_name, jobs_list):
    """Sends an automated email notification with high-match jobs."""
    if not to_email or "@" not in to_email:
        print("⚠️ Valid receiver email not found in candidate profile.")
        return False

    subject = (
        f"🎯 AI Job Match Alert: {len(jobs_list)} New Positions Detected!"
    )

    # Build HTML for all matched jobs
    jobs_cards_html = ""
    for job in jobs_list:
        matched_str = (
            ", ".join(job.get("matched", []))
            if job.get("matched")
            else "Relevant Skills"
        )
        url_str = job.get("url", "#")
        jobs_cards_html += f"""
        <div style="background: #f4f7f6; padding: 15px; border-radius: 8px; border-left: 4px solid #0066cc; margin-bottom: 15px;">
            <p style="margin: 4px 0;"><strong>Job Role:</strong> {job.get('title')}</p>
            <p style="margin: 4px 0;"><strong>Company:</strong> {job.get('company')}</p>
            <p style="margin: 4px 0;"><strong>Match Score:</strong> <span style="color: green; font-weight: bold;">{job.get('score')}%</span></p>
            <p style="margin: 4px 0;"><strong>Matched Skills:</strong> {matched_str}</p>
            <p style="margin-top: 10px;">
                <a href="{url_str}" style="background-color: #28a745; color: white; padding: 6px 14px; text-decoration: none; border-radius: 4px; font-weight: bold; display: inline-block;">
                    View & Apply
                </a>
            </p>
        </div>
        """

    body_html = f"""
    <html>
      <body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333;">
        <h2 style="color: #0066cc;">Hello {candidate_name},</h2>
        <p>Your Autonomous AI Job Agent detected new job openings matching your profile:</p>
        
        {jobs_cards_html}

        <br>
        <p style="font-size: 12px; color: #777;">This alert was automatically generated by your AI Job Agent.</p>
      </body>
    </html>
    """

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = SENDER_EMAIL
    msg["To"] = to_email
    msg.attach(MIMEText(body_html, "html"))

    try:
        server = smtplib.SMTP_SSL("smtp.gmail.com", 465)
        server.login(SENDER_EMAIL, APP_PASSWORD)
        server.sendmail(SENDER_EMAIL, to_email, msg.as_string())
        server.quit()
        print(f"📧 Notification email sent to {to_email} successfully!")
        return True
    except Exception as e:
        print(f"❌ Failed to send email: {e}")
        return 